development:
  adapter: postgresql
  encoding: unicode
  database: car_listings_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: car_listings_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: car_listings_production
  pool: 5
  username: 
  password:
